import { getPool } from '../config/database';
import {
  Match,
  SetScore,
  CreateMatchDto,
  UpdateMatchDto,
  ScoreUpdate,
  ValidationResult,
} from '../types';
import { NotFoundError, ValidationError } from '../middleware/errorHandler';
import { validate } from '../middleware/validation';
import { standingsCalculator } from './standings.service';
import { bracketGenerator } from './bracket.service';
import { fixtureGenerator } from './fixture.service';
import { pushService, ensureReady as ensurePushReady } from './push.service';

/**
 * Fire-and-forget helper that builds the two-team label used in push
 * titles. Falls back to "Partido de voley" when we couldn't join the team
 * rows (shouldn't happen but a push should never fail a match write).
 */
async function matchHeadline(matchId: string): Promise<{ title: string; url: string }> {
  const pool = getPool();
  const result = await pool.query(
    `SELECT m.id, m.tournament_id,
            t1.name AS t1_name, t1.initials AS t1_initials,
            t2.name AS t2_name, t2.initials AS t2_initials
     FROM matches m
     LEFT JOIN teams t1 ON m.team1_id = t1.id
     LEFT JOIN teams t2 ON m.team2_id = t2.id
     WHERE m.id = $1`,
    [matchId],
  );
  if (result.rows.length === 0) {
    return { title: 'Partido de voley', url: '/' };
  }
  const row = result.rows[0];
  const team1 = (row.t1_name as string) || (row.t1_initials as string) || 'Equipo 1';
  const team2 = (row.t2_name as string) || (row.t2_initials as string) || 'Equipo 2';
  return {
    title: `${team1} vs ${team2}`,
    url: `/match/${matchId}`,
  };
}

/**
 * Recalculate standings and re-resolve any bracket placeholders for a
 * tournament. Called after every match mutation that could affect either.
 * Bracket re-resolution is wrapped in try/catch because it's best-effort:
 * tournaments without a bracket, or with bracket matches that have no
 * placeholders, should still succeed on the standings side.
 */
async function refreshTournamentState(tournamentId: string): Promise<void> {
  await standingsCalculator.recalculate(tournamentId);
  try {
    await bracketGenerator.resolveBracketFromStandings(tournamentId);
  } catch {
    // swallow — bracket refresh is best-effort
  }
  try {
    // Division-mode tournaments auto-seed Oro/Plata the moment every
    // group match for a category wraps up. The call is idempotent
    // (skips categories that already have a bracket), so running it
    // after every score write is safe and cheap.
    await fixtureGenerator.autoGenerateDivisionBrackets(tournamentId);
  } catch {
    // swallow — auto-bracket is best-effort, never blocks a score save
  }
}

function mapRow(row: Record<string, unknown>): Match {
  return {
    id: row.id as string,
    tournamentId: row.tournament_id as string,
    team1Id: row.team1_id as string,
    team2Id: row.team2_id as string,
    date: row.date as string,
    time: row.time as string,
    court: row.court as string,
    referee: row.referee as string | undefined,
    status: row.status as Match['status'],
    scoreTeam1: row.score_team1 != null ? (row.score_team1 as number) : undefined,
    scoreTeam2: row.score_team2 != null ? (row.score_team2 as number) : undefined,
    phase: row.phase as string,
    groupName: row.group_name as string | undefined,
    duration: row.duration != null ? (row.duration as number) : undefined,
    createdAt: row.created_at as string | undefined,
    updatedAt: row.updated_at as string | undefined,
  };
}

function mapSetRow(row: Record<string, unknown>): SetScore {
  return {
    id: row.id as string,
    matchId: row.match_id as string,
    setNumber: row.set_number as number,
    team1Points: row.team1_points as number,
    team2Points: row.team2_points as number,
  };
}

/**
 * Context used when listing matches. Public + super_admin see everything;
 * admins see matches of their own tournaments; judges see only LIVE
 * matches from tournaments owned by the admin that created them.
 */
export type MatchListScope =
  | { scope: 'all' }
  | { scope: 'owner'; ownerId: string }
  | { scope: 'judge'; judgeCreatedBy: string };

export class MatchService {
  async getAll(scope: MatchListScope = { scope: 'all' }): Promise<Match[]> {
    const pool = getPool();
    if (scope.scope === 'judge') {
      // Judges see only live matches from tournaments owned by the admin
      // who created them. The join with tournaments is how we enforce the
      // cross-tenant isolation in a single query instead of two round-trips.
      const result = await pool.query(
        `SELECT m.* FROM matches m
         JOIN tournaments t ON m.tournament_id = t.id
         WHERE t.owner_id = $1 AND m.status = 'live'
         ORDER BY m.date, m.time`,
        [scope.judgeCreatedBy],
      );
      const matches = result.rows.map(mapRow);
      return this.attachSets(matches);
    }
    if (scope.scope === 'owner') {
      const result = await pool.query(
        `SELECT m.* FROM matches m
         JOIN tournaments t ON m.tournament_id = t.id
         WHERE t.owner_id = $1
         ORDER BY m.date, m.time`,
        [scope.ownerId],
      );
      const matches = result.rows.map(mapRow);
      return this.attachSets(matches);
    }
    const result = await pool.query('SELECT * FROM matches ORDER BY date, time');
    const matches = result.rows.map(mapRow);
    return this.attachSets(matches);
  }

  async getById(id: string): Promise<Match> {
    const pool = getPool();
    const result = await pool.query('SELECT * FROM matches WHERE id = $1', [id]);
    if (result.rows.length === 0) {
      throw new NotFoundError('Partido');
    }
    const match = mapRow(result.rows[0]);
    const sets = await this.getSets(id);
    match.sets = sets;
    return match;
  }

  async getByTournament(tournamentId: string): Promise<Match[]> {
    // Verify tournament exists
    const pool = getPool();
    const tournamentCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [tournamentId]);
    if (tournamentCheck.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }
    const result = await pool.query(
      'SELECT * FROM matches WHERE tournament_id = $1 ORDER BY date, time',
      [tournamentId]
    );
    const matches = result.rows.map(mapRow);
    return this.attachSets(matches);
  }

  async create(data: CreateMatchDto): Promise<Match> {
    await this.validateData(data);
    const pool = getPool();
    const result = await pool.query(
      `INSERT INTO matches (tournament_id, team1_id, team2_id, date, time, court, referee, phase, group_name)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [
        data.tournamentId,
        data.team1Id,
        data.team2Id,
        data.date,
        data.time,
        data.court,
        data.referee || null,
        data.phase,
        data.groupName || null,
      ]
    );
    return mapRow(result.rows[0]);
  }

  async update(id: string, data: UpdateMatchDto): Promise<Match> {
    // Ensure match exists
    const existing = await this.getById(id);

    // If updating team references, validate them
    if (data.team1Id !== undefined || data.team2Id !== undefined || data.tournamentId !== undefined) {
      const mergedTeam1 = data.team1Id ?? existing.team1Id;
      const mergedTeam2 = data.team2Id ?? existing.team2Id;
      const mergedTournament = data.tournamentId ?? existing.tournamentId;

      if (mergedTeam1 === mergedTeam2) {
        throw new ValidationError('Los dos equipos deben ser diferentes');
      }

      const pool = getPool();
      if (data.tournamentId !== undefined) {
        const tCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [mergedTournament]);
        if (tCheck.rows.length === 0) {
          throw new NotFoundError('Torneo');
        }
      }
      if (data.team1Id !== undefined) {
        const t1Check = await pool.query('SELECT id FROM teams WHERE id = $1', [mergedTeam1]);
        if (t1Check.rows.length === 0) {
          throw new NotFoundError('Equipo 1');
        }
      }
      if (data.team2Id !== undefined) {
        const t2Check = await pool.query('SELECT id FROM teams WHERE id = $1', [mergedTeam2]);
        if (t2Check.rows.length === 0) {
          throw new NotFoundError('Equipo 2');
        }
      }
    }

    const pool = getPool();
    const fields: string[] = [];
    const values: unknown[] = [];
    let idx = 1;

    const columnMap: Record<string, string> = {
      tournamentId: 'tournament_id',
      team1Id: 'team1_id',
      team2Id: 'team2_id',
      date: 'date',
      time: 'time',
      court: 'court',
      referee: 'referee',
      status: 'status',
      scoreTeam1: 'score_team1',
      scoreTeam2: 'score_team2',
      phase: 'phase',
      groupName: 'group_name',
      duration: 'duration',
    };

    for (const [key, column] of Object.entries(columnMap)) {
      if ((data as Record<string, unknown>)[key] !== undefined) {
        fields.push(`${column} = $${idx}`);
        values.push((data as Record<string, unknown>)[key]);
        idx++;
      }
    }

    if (fields.length === 0) {
      return this.getById(id);
    }

    fields.push('updated_at = NOW()');
    values.push(id);

    const query = `UPDATE matches SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`;
    const result = await pool.query(query, values);

    // Recalculate standings if any field that affects them changed.
    // This catches admin edits that save scores / flip status / move a match
    // to a different group, none of which previously triggered the recalc.
    const standingsAffectingFields = [
      'status',
      'scoreTeam1',
      'scoreTeam2',
      'team1Id',
      'team2Id',
      'groupName',
      'tournamentId',
    ];
    const needsRecalc = standingsAffectingFields.some(
      (f) => (data as Record<string, unknown>)[f] !== undefined,
    );
    if (needsRecalc) {
      const tournamentId = (data.tournamentId ?? existing.tournamentId) as string;
      await refreshTournamentState(tournamentId);
    }

    // Fire a push when the admin flips a match into 'live' from here.
    // Score corrections from the admin form skip the score-push flow —
    // that belongs to the referee console where the judge drives scoring.
    if (data.status === 'live' && existing.status !== 'live') {
      ensurePushReady()
        .then((keys) => {
          if (!keys) return;
          return matchHeadline(id).then(({ title, url }) =>
            pushService.sendToAll({
              title: `${title} · En vivo`,
              body: '¡El partido acaba de comenzar!',
              url,
              tag: `match-live-${id}`,
              data: { matchId: id, type: 'match-live' },
            }),
          );
        })
        .catch((err) => console.warn('[push] match-live dispatch failed', err));
    }

    return mapRow(result.rows[0]);
  }

  async updateScore(id: string, score: ScoreUpdate): Promise<Match> {
    // Ensure match exists
    const existing = await this.getById(id);
    const pool = getPool();

    // Validate set points are non-negative integers
    if (score.sets) {
      for (const set of score.sets) {
        if (!Number.isInteger(set.setNumber) || set.setNumber < 1 || set.setNumber > 5) {
          throw new ValidationError('El número de set debe ser un entero entre 1 y 5');
        }
        if (!Number.isInteger(set.team1Points) || set.team1Points < 0) {
          throw new ValidationError('Los puntos del equipo 1 deben ser un entero no negativo');
        }
        if (!Number.isInteger(set.team2Points) || set.team2Points < 0) {
          throw new ValidationError('Los puntos del equipo 2 deben ser un entero no negativo');
        }
      }
    }

    if (score.duration !== undefined && (score.duration <= 0 || !Number.isInteger(score.duration))) {
      throw new ValidationError('La duración debe ser un entero positivo');
    }

    // Update match fields
    const fields: string[] = [];
    const values: unknown[] = [];
    let idx = 1;

    if (score.status !== undefined) {
      fields.push(`status = $${idx}`);
      values.push(score.status);
      idx++;
    }
    if (score.scoreTeam1 !== undefined) {
      fields.push(`score_team1 = $${idx}`);
      values.push(score.scoreTeam1);
      idx++;
    }
    if (score.scoreTeam2 !== undefined) {
      fields.push(`score_team2 = $${idx}`);
      values.push(score.scoreTeam2);
      idx++;
    }
    if (score.duration !== undefined) {
      fields.push(`duration = $${idx}`);
      values.push(score.duration);
      idx++;
    }

    if (fields.length > 0) {
      fields.push('updated_at = NOW()');
      values.push(id);
      const query = `UPDATE matches SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`;
      await pool.query(query, values);
    }

    // Upsert sets and remove deleted ones
    if (score.sets) {
      if (score.sets.length > 0) {
        // Delete sets that are no longer in the list
        const setNumbers = score.sets.map(s => s.setNumber);
        await pool.query(
          'DELETE FROM set_scores WHERE match_id = $1 AND set_number != ALL($2)',
          [id, setNumbers]
        );
        for (const set of score.sets) {
          await pool.query(
            `INSERT INTO set_scores (match_id, set_number, team1_points, team2_points)
             VALUES ($1, $2, $3, $4)
             ON CONFLICT (match_id, set_number)
             DO UPDATE SET team1_points = $3, team2_points = $4`,
            [id, set.setNumber, set.team1Points, set.team2Points]
          );
        }
      } else {
        // Empty sets array means remove all sets
        await pool.query('DELETE FROM set_scores WHERE match_id = $1', [id]);
      }
    }

    // Recalculate standings whenever a score update touches anything that
    // affects them — set changes, score_team1/2 changes, status changes,
    // or any other field the referee / admin might edit. Previously we
    // only recalculated on the upcoming→completed transition, which meant
    // subsequent score corrections didn't update the table.
    const scoreTouched =
      score.sets !== undefined ||
      score.scoreTeam1 !== undefined ||
      score.scoreTeam2 !== undefined ||
      score.status !== undefined;
    if (scoreTouched) {
      await refreshTournamentState(existing.tournamentId);
    }

    // Push dispatch (fire-and-forget):
    //   - status transitions to 'live'      → "En vivo" notification
    //   - a set just got decided            → "Set N cerrado" notification
    //   - status transitions to 'completed' → "Final" notification
    //
    // IMPORTANT: we count only DECIDED sets (one side ≥ 25 points with 2
    // of ventaja, or ≥ 15 with 2 in a 5th), NOT the raw array length.
    // The RefereeScore autosave now persists the in-progress set as the
    // last row in set_scores so the public + re-entry work correctly —
    // using `score.sets.length` here would fire a spurious "Set 1 cerrado"
    // on the very first point of every set, and skip real closures (the
    // array length stays the same between "Set 1 at 24-20" and "Set 1
    // closed at 25-20").
    const becameLive = score.status === 'live' && existing.status !== 'live';
    const becameCompleted = score.status === 'completed' && existing.status !== 'completed';
    const decidedSetsCount = (sets: Array<{ setNumber: number; team1Points: number; team2Points: number }> | undefined) => {
      if (!sets) return 0;
      let n = 0;
      for (const s of sets) {
        const target = s.setNumber >= 5 ? 15 : 25;
        const top = Math.max(s.team1Points, s.team2Points);
        const diff = Math.abs(s.team1Points - s.team2Points);
        if (top >= target && diff >= 2) n++;
      }
      return n;
    };
    const previousDecidedSets = decidedSetsCount(existing.sets);
    const newDecidedSets = decidedSetsCount(score.sets);
    const setJustClosed = newDecidedSets > previousDecidedSets;

    if (becameLive || becameCompleted || setJustClosed) {
      const notify = async () => {
        const keys = await ensurePushReady();
        if (!keys) return;
        const { title, url } = await matchHeadline(id);
        if (becameCompleted) {
          const setsH = (score.sets ?? []).filter((s) => s.team1Points > s.team2Points).length;
          const setsA = (score.sets ?? []).filter((s) => s.team2Points > s.team1Points).length;
          await pushService.sendToAll({
            title: `${title} · Final`,
            body: `Resultado ${setsH}–${setsA}. Tocá para ver el detalle.`,
            url,
            tag: `match-final-${id}`,
            data: { matchId: id, type: 'match-completed' },
          });
          return;
        }
        if (setJustClosed && score.sets) {
          const last = score.sets[score.sets.length - 1];
          const setsH = score.sets.filter((s) => s.team1Points > s.team2Points).length;
          const setsA = score.sets.filter((s) => s.team2Points > s.team1Points).length;
          await pushService.sendToAll({
            title: `${title} · Set ${score.sets.length} cerrado`,
            body: `${last.team1Points}–${last.team2Points} · Sets ${setsH}–${setsA}`,
            url,
            tag: `match-score-${id}`,
            data: { matchId: id, type: 'set-closed' },
          });
          return;
        }
        if (becameLive) {
          await pushService.sendToAll({
            title: `${title} · En vivo`,
            body: '¡El partido acaba de comenzar!',
            url,
            tag: `match-live-${id}`,
            data: { matchId: id, type: 'match-live' },
          });
        }
      };
      notify().catch((err) => console.warn('[push] match dispatch failed', err));
    }

    return this.getById(id);
  }

  async delete(id: string): Promise<void> {
    // Snapshot the tournament id before the row is gone so we can
    // recalculate the standings once the match is out of the picture.
    const existing = await this.getById(id);
    const pool = getPool();
    // set_scores are deleted via CASCADE
    await pool.query('DELETE FROM matches WHERE id = $1', [id]);
    await refreshTournamentState(existing.tournamentId);
  }

  async validateData(data: CreateMatchDto): Promise<ValidationResult> {
    validate(data as unknown as Record<string, unknown>, [
      { field: 'tournamentId', label: 'Torneo', required: true, type: 'string' },
      { field: 'team1Id', label: 'Equipo 1', required: true, type: 'string' },
      { field: 'team2Id', label: 'Equipo 2', required: true, type: 'string' },
      { field: 'date', label: 'Fecha', required: true, type: 'string' },
      { field: 'time', label: 'Hora', required: true, type: 'string' },
      { field: 'court', label: 'Cancha', required: true, type: 'string' },
      { field: 'phase', label: 'Fase', required: true, type: 'string' },
    ]);

    // Validate teams are different
    if (data.team1Id === data.team2Id) {
      throw new ValidationError('Los dos equipos deben ser diferentes');
    }

    // Validate tournament exists
    const pool = getPool();
    const tournamentCheck = await pool.query('SELECT id FROM tournaments WHERE id = $1', [data.tournamentId]);
    if (tournamentCheck.rows.length === 0) {
      throw new NotFoundError('Torneo');
    }

    // Validate team1 exists
    const team1Check = await pool.query('SELECT id FROM teams WHERE id = $1', [data.team1Id]);
    if (team1Check.rows.length === 0) {
      throw new NotFoundError('Equipo 1');
    }

    // Validate team2 exists
    const team2Check = await pool.query('SELECT id FROM teams WHERE id = $1', [data.team2Id]);
    if (team2Check.rows.length === 0) {
      throw new NotFoundError('Equipo 2');
    }

    return { valid: true, errors: [] };
  }

  // --- Private helpers ---

  private async getSets(matchId: string): Promise<SetScore[]> {
    const pool = getPool();
    const result = await pool.query(
      'SELECT * FROM set_scores WHERE match_id = $1 ORDER BY set_number',
      [matchId]
    );
    return result.rows.map(mapSetRow);
  }

  private async attachSets(matches: Match[]): Promise<Match[]> {
    if (matches.length === 0) return matches;
    const pool = getPool();
    const matchIds = matches.map(m => m.id);
    const result = await pool.query(
      'SELECT * FROM set_scores WHERE match_id = ANY($1) ORDER BY set_number',
      [matchIds]
    );
    const setsByMatch = new Map<string, SetScore[]>();
    for (const row of result.rows) {
      const set = mapSetRow(row);
      const existing = setsByMatch.get(set.matchId) || [];
      existing.push(set);
      setsByMatch.set(set.matchId, existing);
    }
    for (const match of matches) {
      match.sets = setsByMatch.get(match.id) || [];
    }
    return matches;
  }
}

export const matchService = new MatchService();
